### ISSUE TITLE
Ruby NLP

### ISSUE THREAD

**Issue by arbox** [mulev/alexa-ruby#8]
Hi Mike,

we've recently added your project to our RubyNLP list: https://github.com/arbox/nlp-with-ruby

I wonder if you want to participate in the Ruby for NLP network. You could do this in a very simple step by adding the `rubynlp` topic to your GitHub repository.  This simple step would enhance the discoverability of your Gem :smiley: 

Thank you for the project!

**Comment by mulev** [comment]
Hi Andrei,

Thanks a lot, it's a great suggestion, added `rubynlp` to my project topics list :)
